pipelines:
  default: 
    - step:
        name: Terraform Plan 
        image: hashicorp/terraform:1.5.7
        script:
          - cd aws_infra
          - terraform init
          - terraform plan -out=tfplan
        artifacts:
          - aws_infra/tfplan 
    - step:
        name: Terraform Apply
        image: hashicorp/terraform:1.5.7
        trigger: automatic
        script:
          - cd aws_infra
          - terraform apply tfplan