name: Build and Deploy

on:
    push:
        branches:
            - master

jobs:
    deploy: 
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: set up Terraform
              uses: hashicorp/setup-terraform@v1

            - name: Terraform Initialize
              run: | 
                cd aws_infra
                terraform init

            - name: Terraform Plan
              run: |
                    cd aws_infra
                    terraform plan
                    if [ $? -eq 0 ]; then  
                        echo "Step two successful: Terraform plan succeeded"
                    else
                        echo "Terraform plan failed" >&2
                        exit 1  # Fail the step if plan fails
                    fi
                    else
                        echo "No Terraform configuration files found in aws_infra directory" >&2
                        exit 1
                    fi
